"""Convert downloaded Confluence HTML pages to Obsidian-compatible Markdown.

Source : pages/<hierarchy>/<Title>/index.html  (generated by sync_confluence.py)
Output : GalenMD/<hierarchy>/<Title>.md

Features
--------
- Obsidian callouts  > [!info] / [!tip] / [!warning] / [!danger] / [!abstract]
- Obsidian wikilinks [[Page Title]] for internal Confluence links
- Vault-absolute image paths  ![[pages/.../assets/filename.png]]
- GFM tables, fenced code blocks, nested lists
- YAML frontmatter from meta.json
- Incremental: skips pages where version in frontmatter matches meta.json
- Does NOT modify pages/ data
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import warnings
from pathlib import Path
from typing import NamedTuple

from bs4 import BeautifulSoup, NavigableString, Tag, XMLParsedAsHTMLWarning

warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ── Regexes ──────────────────────────────────────────────────────────────────

CONFLUENCE_PAGE_URL = re.compile(
    r"https?://stapro-galen\.atlassian\.net/wiki/spaces/\w+/pages/(\d+)"
)
MULTI_BLANK = re.compile(r"\n{3,}")
TRAIL_SPACE = re.compile(r"[ \t]+\n")
ANCHOR_ID = re.compile(r"^[\w%-]+-")        # strip "PageTitle-" prefix from heading IDs


# ── Context ───────────────────────────────────────────────────────────────────

class ConvCtx(NamedTuple):
    page_dir: Path          # pages/<hierarchy>/<Title>
    out_root: Path          # repo root
    link_map: dict          # {page_id: {"title": ..., "path": ...}}


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_link_map(out_root: Path) -> dict:
    idx = out_root / "_meta" / "index.json"
    if not idx.exists():
        return {}
    return json.loads(idx.read_text(encoding="utf-8")).get("pages", {})


def vault_asset_path(src: str, ctx: ConvCtx) -> str:
    """Convert './assets/X' → vault-absolute 'pages/.../assets/X'."""
    if not src.startswith("./assets/"):
        return src
    filename = src[len("./assets/"):]
    rel = ctx.page_dir.relative_to(ctx.out_root)
    return str(rel / "assets" / filename).replace("\\", "/")


def resolve_internal_link(href: str, resource_id: str, ctx: ConvCtx) -> str | None:
    """Return page title for wikilink, or None if unresolvable."""
    if resource_id and resource_id in ctx.link_map:
        return ctx.link_map[resource_id]["title"]
    if href:
        m = CONFLUENCE_PAGE_URL.search(href)
        if m and m.group(1) in ctx.link_map:
            return ctx.link_map[m.group(1)]["title"]
    return None


def prefix_callout(text: str) -> str:
    """Prefix every line of text with '> ' for callout body."""
    lines = text.rstrip("\n").split("\n")
    return "\n".join(("> " + l) if l.strip() else ">" for l in lines)


def format_callout(kind: str, content: str, title: str = "", collapsed: bool = False) -> str:
    marker = f"> [!{kind}]" + ("-" if collapsed else "") + (f" {title.strip()}" if title.strip() else "")
    if not content.strip():
        return marker + "\n\n"
    return marker + "\n" + prefix_callout(content.strip()) + "\n\n"


# ── Core converter ────────────────────────────────────────────────────────────

SKIP_TAGS = {"style", "script", "meta", "link", "head"}
INLINE_TAGS = {"span", "small", "abbr", "cite", "kbd", "mark", "samp", "var"}
TRANSPARENT_DIVS = {
    "innerCell", "cell", "columnLayout", "sectionLayout", "contentLayout2",
    "table-wrap", "confluence-information-macro-body",
    "image-wrap", "confluence-embedded-file-wrapper",
    "expand-content",
}
MACRO_CALLOUT = {
    "confluence-information-macro-information": "info",
    "confluence-information-macro-tip":         "tip",
    "confluence-information-macro-note":        "warning",
    "confluence-information-macro-warning":     "danger",
}


def children(node: Tag, ctx: ConvCtx) -> str:
    return "".join(node_to_md(c, ctx) for c in node.children)


def node_to_md(node, ctx: ConvCtx) -> str:  # noqa: C901
    # ── Plain text ──
    if isinstance(node, NavigableString):
        return str(node).replace("\xa0", " ")

    if not isinstance(node, Tag):
        return ""

    tag = node.name or ""
    cls: list[str] = node.get("class") or []

    # ── Skip ──
    if tag in SKIP_TAGS:
        return ""
    if "toc-macro" in cls or any(c.startswith("rbtoc") for c in cls):
        return ""
    if "waiting-image" in cls:
        return ""
    if "confluence-information-macro-icon" in cls or "aui-icon" in cls:
        return ""
    if tag == "header":             # our generated metadata header
        return ""

    # ── Headings ──
    if tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
        level = int(tag[1])
        text = children(node, ctx).strip()
        return f"\n{'#' * level} {text}\n\n"

    # ── Block elements ──
    if tag == "p":
        text = children(node, ctx).strip()
        return (text + "\n\n") if text else ""

    if tag in ("strong", "b"):
        text = children(node, ctx).strip()
        return f"**{text}**" if text else ""

    if tag in ("em", "i"):
        text = children(node, ctx).strip()
        return f"*{text}*" if text else ""

    if tag in ("s", "del", "strike"):
        text = children(node, ctx).strip()
        return f"~~{text}~~" if text else ""

    if tag == "sup":
        return f"^{children(node, ctx).strip()}^"

    if tag == "sub":
        return f"~{children(node, ctx).strip()}~"

    # ── Code ──
    if tag == "code":
        if node.parent and node.parent.name == "pre":
            return children(node, ctx)
        return f"`{children(node, ctx)}`"

    if tag == "pre":
        lang = ""
        code_tag = node.find("code")
        if code_tag:
            for c in (code_tag.get("class") or []):
                m = re.match(r"language-(\w+)", c)
                if m:
                    lang = m.group(1)
        params = node.get("data-syntaxhighlighter-params", "")
        m = re.search(r"language=(\w+)", params)
        if m:
            lang = m.group(1)
        inner = children(node, ctx).strip()
        return f"\n```{lang}\n{inner}\n```\n\n"

    # ── Inline ──
    if tag == "br":
        return "\n"

    if tag == "hr":
        return "\n---\n\n"

    # ── Links ──
    if tag == "a":
        text = children(node, ctx).strip()
        if not text:
            return ""
        href = node.get("href", "")
        rid = node.get("data-linked-resource-id", "")
        title = resolve_internal_link(href, rid, ctx)
        if title:
            return f"[[{title}|{text}]]" if text != title else f"[[{title}]]"
        if href.startswith("#"):
            return text
        return f"[{text}]({href})" if href else text

    # ── Images ──
    if tag == "img":
        if "waiting-image" in cls:
            return ""
        src = node.get("src", "")
        alt = node.get("alt", "")
        if src.startswith("./assets/"):
            return f"![[{vault_asset_path(src, ctx)}]]\n"
        if src.startswith("http"):
            return f"![{alt}]({src})\n"
        return ""

    # ── Lists ──
    if tag in ("ul", "ol"):
        items = []
        for i, li in enumerate(node.find_all("li", recursive=False), 1):
            inner = children(li, ctx).strip()
            lines = inner.split("\n")
            result_lines: list[str] = []
            for j, line in enumerate(lines):
                if j == 0:
                    prefix = f"{i}. " if tag == "ol" else "- "
                    result_lines.append(prefix + line)
                elif line.strip():
                    result_lines.append("   " + line)
                else:
                    result_lines.append("")
            items.append("\n".join(result_lines))
        return "\n".join(items) + "\n\n" if items else ""

    if tag == "li":
        return "- " + children(node, ctx).strip() + "\n"

    # ── Blockquote ──
    if tag == "blockquote":
        text = children(node, ctx).strip()
        return "\n".join(f"> {l}" if l.strip() else ">" for l in text.split("\n")) + "\n\n"

    # ── Table ──
    if tag == "table":
        return convert_table(node, ctx)

    if tag in ("thead", "tbody", "tfoot", "colgroup", "col"):
        return children(node, ctx)

    if tag in ("tr", "th", "td"):
        return children(node, ctx)

    # ── Confluence info macros ──
    for macro_cls, callout_kind in MACRO_CALLOUT.items():
        if macro_cls in cls:
            body = node.find(class_="confluence-information-macro-body")
            inner = children(body, ctx) if body else children(node, ctx)
            return format_callout(callout_kind, inner.strip())

    # ── Panel ──
    if "panel" in cls:
        header_tag = node.find(class_="panelHeader")
        body_tag = node.find(class_="panelContent")
        panel_title = children(header_tag, ctx).strip() if header_tag else ""
        inner = children(body_tag, ctx) if body_tag else children(node, ctx)
        return format_callout("abstract", inner.strip(), title=panel_title)

    # ── Expand (collapsible) ──
    if "expand-container" in cls:
        ctrl = node.find(class_="expand-control")
        body_tag = node.find(class_="expand-content")
        expand_title = children(ctrl, ctx).strip() if ctrl else "Zobrazit"
        inner = children(body_tag, ctx) if body_tag else children(node, ctx)
        return format_callout("summary", inner.strip(), title=expand_title, collapsed=True)

    # ── Transparent wrappers ──
    if any(c in cls for c in TRANSPARENT_DIVS):
        return children(node, ctx)

    # ── Generic block containers ──
    if tag in ("div", "section", "article", "main", "figure", "figcaption", "aside"):
        return children(node, ctx)

    # ── Inline containers ──
    if tag in INLINE_TAGS or tag == "span":
        return children(node, ctx)

    # ── Fallback ──
    return children(node, ctx)


# ── Table conversion ──────────────────────────────────────────────────────────

def convert_table(table: Tag, ctx: ConvCtx) -> str:
    rows = table.find_all("tr")
    if not rows:
        return ""

    matrix: list[list[str]] = []
    has_header = False

    for tr in rows:
        cells = tr.find_all(["th", "td"])
        if tr.find("th"):
            has_header = True
        row = []
        for cell in cells:
            text = children(cell, ctx).strip()
            text = re.sub(r"\n+", " ", text).replace("|", "\\|").strip()
            row.append(text)
        matrix.append(row)

    if not matrix:
        return ""

    max_cols = max(len(r) for r in matrix)
    for r in matrix:
        r += [""] * (max_cols - len(r))

    lines = []
    for i, row in enumerate(matrix):
        lines.append("| " + " | ".join(row) + " |")
        if i == 0:
            lines.append("| " + " | ".join(["---"] * max_cols) + " |")

    return "\n" + "\n".join(lines) + "\n\n"


# ── Page conversion ───────────────────────────────────────────────────────────

def page_to_markdown(html: str, meta: dict, ctx: ConvCtx) -> str:
    soup = BeautifulSoup(html, "html.parser")
    main = soup.find("main")
    if not main:
        return ""

    md = node_to_md(main, ctx)

    # Post-process
    md = MULTI_BLANK.sub("\n\n", md)
    md = TRAIL_SPACE.sub("\n", md)
    md = md.strip()

    title = meta.get("title", "")
    version = meta.get("version", "")
    updated_at = str(meta.get("updated_at") or "")[:10]
    source = meta.get("source", "")

    frontmatter = (
        f"---\n"
        f"title: {json.dumps(title, ensure_ascii=False)}\n"
        f"version: {version}\n"
        f"updated_at: {updated_at}\n"
        f"source: {source}\n"
        f"---\n\n"
    )
    return frontmatter + md + "\n"


# ── Main ──────────────────────────────────────────────────────────────────────

VERSION_RE = re.compile(r"^version:\s*(\S+)", re.MULTILINE)


def convert_all(out_root: Path, galenmd_root: Path, force: bool = False) -> dict:
    link_map = load_link_map(out_root)
    print(f"Loaded {len(link_map)} pages in link map")

    pages_root = out_root / "pages"
    if not pages_root.exists():
        raise RuntimeError("pages/ directory not found")

    galenmd_root.mkdir(parents=True, exist_ok=True)

    stats = {"total": 0, "converted": 0, "skipped": 0}

    for meta_file in sorted(pages_root.rglob("meta.json")):
        page_dir = meta_file.parent
        idx_html = page_dir / "index.html"
        if not idx_html.exists():
            continue

        rel = page_dir.relative_to(pages_root)
        md_path = galenmd_root / (str(rel) + ".md")

        meta = json.loads(meta_file.read_text(encoding="utf-8"))
        current_version = meta.get("version")
        stats["total"] += 1

        # Skip if version unchanged
        if not force and md_path.exists():
            existing = md_path.read_text(encoding="utf-8")
            m = VERSION_RE.search(existing)
            if m and m.group(1) == str(current_version):
                stats["skipped"] += 1
                continue

        print(f"  {meta.get('title', str(rel))}")

        ctx = ConvCtx(page_dir=page_dir, out_root=out_root, link_map=link_map)
        html = idx_html.read_text(encoding="utf-8")
        md = page_to_markdown(html, meta, ctx)

        md_path.parent.mkdir(parents=True, exist_ok=True)
        md_path.write_text(md, encoding="utf-8", newline="\n")
        stats["converted"] += 1

    return stats


def main() -> int:
    ap = argparse.ArgumentParser(description="Convert Confluence HTML → Obsidian Markdown")
    ap.add_argument("--out",     default=".",        help="Repo root (contains pages/ and _meta/)")
    ap.add_argument("--galenmd", default="GalenMD",  help="Output directory (default: GalenMD)")
    ap.add_argument("--force",   action="store_true", help="Reconvert all pages even if version unchanged")
    args = ap.parse_args()

    out_root    = Path(args.out).resolve()
    galenmd_dir = Path(args.galenmd) if Path(args.galenmd).is_absolute() else out_root / args.galenmd

    print(f"Output: {galenmd_dir}")
    stats = convert_all(out_root, galenmd_dir, force=args.force)
    print(f"\nHotovo: {stats['converted']} konvertováno, {stats['skipped']} přeskočeno, {stats['total']} celkem")
    return 0


if __name__ == "__main__":
    sys.exit(main())
